services:
  vue-app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: vue-img-prod:latest
    container_name: vue-container
    ports:
      - 80:8080 # localport:dockerport
    volumes:
      - ./:/app
